# Generated by Django 4.2.5 on 2023-10-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='desc',
            new_name='DES',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='img',
            new_name='IMG',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='NAME',
        ),
    ]
