# Generated by Django 4.2.5 on 2023-10-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0002_rename_desc_place_des_rename_img_place_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='DES',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='NAME',
            new_name='State',
        ),
    ]
