# Generated by Django 4.2.5 on 2023-10-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0004_place_area_place_bathroom_place_bedroom_place_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='State',
            new_name='City',
        ),
    ]
